version: '3'

services:
#  db:
#    image: postgres:9.6.5
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"

  celery:
    build: .
    # command: celery -A NewsPaper worker -l info # command for sending emails
    command: celery -A NewsPaper worker -l info -B #command for periodical tasks
    volumes:
      - .:/code
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A NewsPaper worker -l INFO -B
    #command: celery -A NewsPaper worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis

#volumes:
#  postgres_data: