# Generated by Django 3.2.3 on 2021-08-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
