# Generated by Django 3.2.3 on 2021-08-25 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_comment_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='category',
            field=models.ManyToManyField(through='news.CommentCategory', to='news.Category'),
        ),
    ]
