# Generated by Django 3.2.3 on 2021-08-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_remove_category_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='category',
        ),
        migrations.DeleteModel(
            name='CommentCategory',
        ),
    ]
