# Generated by Django 3.2.3 on 2021-08-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20210825_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
    ]
